graph TD

    pico-character(FOCUS Pico Character)
    class pico-character focus

    mentors(CONN Mentors)
    pico-character --> mentors
    class mentors connected
    amara-narrative(CONN Amara Narrat)
    pico-character --> amara-narrative
    class amara-narrative connected

    classDef focus fill:#ff6348,stroke:#ff3838,color:#fff
    classDef connected fill:#7bed9f,stroke:#5f27cd,color:#fff